### ISSUE TITLE
No license chosen for the repository

### ISSUE THREAD

**Issue by gerzytet** [jamchamb/ac-nesrom-save-generator#1]
Hello!

I am interested in using this program, but while attempting to run it, I found that it only runs in python 2.
I have decided to try porting this code to python 3, so I would need to modify it.  I would also like others to benefit from my modification, but this requires permission to distribute a derivative work.
Please either add a license, or give me personal permission to use your code.

**Comment by jamchamb** [comment]
Hi, I added an open source license to the project (GPL).
